function com_google_gwt_demos_datepicker_DatePickerDemo(){var l='',B='" for "gwt:onLoadErrorFn"',z='" for "gwt:onPropertyErrorFn"',zb='"><\/script>',n='/',mb='609CE4E5FD70153416294A4B87234187.cache.html',ib='6242DD41E7986201A1D579864C94EC63.cache.html',kb='87457A5347BD18D3F0AF782325ACDFB8.cache.html',lb='9F7D90EF1DB7B68BBA685AB2D0D1F11B.cache.html',tb='<link rel="stylesheet" href="',yb='<script id="',vb="<script>com_google_gwt_demos_datepicker_DatePickerDemo.onInjectionDone('com.google.gwt.demos.datepicker.DatePickerDemo')<\/script>",v='=',jb='B888028BE46BDD5CAD4F15CFB9F30B58.cache.html',y='Bad handler "',ob='DOMContentLoaded',sb='DatePickerDemo.css',ub='DatePickerDemo.css">',Ab='SCRIPT',xb='__gwt_marker_com.google.gwt.demos.datepicker.DatePickerDemo',o='base',q='clear.cache.gif',m='com.google.gwt.demos.datepicker.DatePickerDemo',u='content',db='gecko',eb='gecko1_8',nb='gwt.hybrid',A='gwt:onLoadErrorFn',w='gwt:onPropertyErrorFn',t='gwt:property',hb='hosted.html?com_google_gwt_demos_datepicker_DatePickerDemo',bb='ie6',pb='iframe',p='img',qb="javascript:''",r='meta',gb='moduleRequested',ab='msie',s='name',D='opera',rb='position:absolute;width:0;height:0;border:none',F='safari',wb='selectionDone',cb='selectionStart',x='startup',fb='unknown',C='user.agent',E='webkit';var Cb=window,k=document,ec=Cb.external,Bb=Cb.__gwtstatsEvent?function(a,b,c,d){Cb.__gwtstatsEvent(a,b,c,d)}:null,rc,hc,bc,ac=l,kc={},uc=[],qc=[],Fb=[],nc,pc;Bb&&Bb(m,x,cb,{millis:(new Date()).getTime()});if(!Cb.__gwt_stylesLoaded){Cb.__gwt_stylesLoaded={}}if(!Cb.__gwt_scriptsLoaded){Cb.__gwt_scriptsLoaded={}}function gc(){try{return ec&&(ec.gwtOnLoad&&Cb.location.search.indexOf(nb)==-1)}catch(a){return false}}
function jc(){if(rc&&hc){var c=k.getElementById(m);var b=c.contentWindow;b.__gwt_initHandlers=com_google_gwt_demos_datepicker_DatePickerDemo.__gwt_initHandlers;if(gc()){b.__gwt_getProperty=function(a){return cc(a)}}com_google_gwt_demos_datepicker_DatePickerDemo=null;b.gwtOnLoad(nc,m,ac);Bb&&Bb(m,x,wb,{millis:(new Date()).getTime()})}}
function dc(){var j,h=xb,i;k.write(yb+h+zb);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=Ab){j=j.previousSibling}function d(b){var a=b.lastIndexOf(n);return a>=0?b.substring(0,a+1):l}
;if(j&&j.src){ac=d(j.src)}if(ac==l){var c=k.getElementsByTagName(o);if(c.length>0){ac=c[c.length-1].href}else{var g=k.location;var e=g.href;ac=d(e.substr(0,e.length-g.hash.length))}}else if(ac.match(/^\w+:\/\//)){}else{var f=k.createElement(p);f.src=ac+q;ac=d(f.src)}if(i){i.parentNode.removeChild(i)}}
function oc(){var f=document.getElementsByTagName(r);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(s),b;if(h){if(h==t){b=e.getAttribute(u);if(b){var i,c=b.indexOf(v);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}kc[h]=i}}else if(h==w){b=e.getAttribute(u);if(b){try{pc=eval(b)}catch(a){alert(y+b+z)}}}else if(h==A){b=e.getAttribute(u);if(b){try{nc=eval(b)}catch(a){alert(y+b+B)}}}}}}
function tc(d,e){var a=Fb;for(var b=0,c=d.length-1;b<c;++b){a=a[d[b]]||(a[d[b]]=[])}a[d[c]]=e}
function cc(d){var e=qc[d](),b=uc[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(pc){pc(d,a,e)}throw null}
qc[C]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(D)!=-1){return D}else if(d.indexOf(E)!=-1){return F}else if(d.indexOf(ab)!=-1){var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=6000){return bb}}}else if(d.indexOf(db)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return eb}return db}return fb};uc[C]={gecko:0,gecko1_8:1,ie6:2,opera:3,safari:4};com_google_gwt_demos_datepicker_DatePickerDemo.onInjectionDone=function(){rc=true;Bb&&Bb(m,x,gb,{millis:(new Date()).getTime()});jc()};com_google_gwt_demos_datepicker_DatePickerDemo.onScriptLoad=function(){hc=true;jc()};dc();oc();var sc;if(gc()){sc=hb}else{try{tc([db],ib);tc([bb],jb);tc([D],kb);tc([F],lb);tc([eb],mb);sc=Fb[cc(C)]}catch(a){return}}var mc;function lc(){if(!bc){bc=true;jc();if(k.removeEventListener){k.removeEventListener(ob,lc,false)}if(mc){clearInterval(mc)}}}
var fc;function ic(){if(!fc){fc=true;var a=k.createElement(pb);a.src=qb;a.id=m;a.style.cssText=rb;a.tabIndex=-1;k.body.appendChild(a);a.src=ac+sc}}
if(k.addEventListener){k.addEventListener(ob,function(){ic();lc()},false)}var mc=setInterval(function(){if(/loaded|complete/.test(k.readyState)){ic();lc()}},50);if(!__gwt_stylesLoaded[sb]){__gwt_stylesLoaded[sb]=true;document.write(tb+ac+ub)}k.write(vb)}
com_google_gwt_demos_datepicker_DatePickerDemo.__gwt_initHandlers=function(i,e,j){var d=window,g=d.onresize,f=d.onbeforeunload,h=d.onunload;d.onresize=function(a){try{i()}finally{g&&g(a)}};d.onbeforeunload=function(a){var c,b;try{c=e()}finally{b=f&&f(a)}if(c!=null){return c}if(b!=null){return b}};d.onunload=function(a){try{j()}finally{h&&h(a)}}};com_google_gwt_demos_datepicker_DatePickerDemo();