function com_google_gwt_demos_spinner_SpinnerDemo(){var l='',B='" for "gwt:onLoadErrorFn"',z='" for "gwt:onPropertyErrorFn"',Cb='"><\/script>',n='/',kb='00CB9DE76C1F3AD0FAFB4F945D6C2AE7.cache.html',lb='0D268DF8EB97E712944AABC654229E5D.cache.html',mb='10D94EDF69887C07DAFF0B38A64BAF69.cache.html',Bb='<script id="',zb="<script>com_google_gwt_demos_spinner_SpinnerDemo.onInjectionDone('com.google.gwt.demos.spinner.SpinnerDemo')<\/script>",v='=',jb='ACA78BAA8397D9FA602F307D64C5E283.cache.html',y='Bad handler "',ib='C75C1B56D985FBFF8C71943253FD966D.cache.html',ub='DOMContentLoaded',Db='SCRIPT',ob='SpinnerDemo.css',Ab='__gwt_marker_com.google.gwt.demos.spinner.SpinnerDemo',o='base',q='clear.cache.gif',m='com.google.gwt.demos.spinner.SpinnerDemo',u='content',db='gecko',eb='gecko1_8',nb='gwt.hybrid',A='gwt:onLoadErrorFn',w='gwt:onPropertyErrorFn',t='gwt:property',tb='head',hb='hosted.html?com_google_gwt_demos_spinner_SpinnerDemo',sb='href',bb='ie6',vb='iframe',p='img',wb="javascript:''",pb='link',r='meta',gb='moduleRequested',ab='msie',s='name',D='opera',xb='position:absolute;width:0;height:0;border:none',qb='rel',F='safari',yb='selectionDone',cb='selectionStart',x='startup',rb='stylesheet',fb='unknown',C='user.agent',E='webkit';var Fb=window,k=document,hc=Fb.external,Eb=Fb.__gwtstatsEvent?function(a,b,c,d){Fb.__gwtstatsEvent(a,b,c,d)}:null,uc,kc,ec,dc=l,nc={},xc=[],tc=[],cc=[],qc,sc;Eb&&Eb(m,x,cb,{millis:(new Date()).getTime()});if(!Fb.__gwt_stylesLoaded){Fb.__gwt_stylesLoaded={}}if(!Fb.__gwt_scriptsLoaded){Fb.__gwt_scriptsLoaded={}}function jc(){try{return hc&&(hc.gwtOnLoad&&Fb.location.search.indexOf(nb)==-1)}catch(a){return false}}
function mc(){if(uc&&kc){var c=k.getElementById(m);var b=c.contentWindow;b.__gwt_initHandlers=com_google_gwt_demos_spinner_SpinnerDemo.__gwt_initHandlers;if(jc()){b.__gwt_getProperty=function(a){return fc(a)}}com_google_gwt_demos_spinner_SpinnerDemo=null;b.gwtOnLoad(qc,m,dc);Eb&&Eb(m,x,yb,{millis:(new Date()).getTime()})}}
function gc(){var j,h=Ab,i;k.write(Bb+h+Cb);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=Db){j=j.previousSibling}function d(b){var a=b.lastIndexOf(n);return a>=0?b.substring(0,a+1):l}
;if(j&&j.src){dc=d(j.src)}if(dc==l){var c=k.getElementsByTagName(o);if(c.length>0){dc=c[c.length-1].href}else{var g=k.location;var e=g.href;dc=d(e.substr(0,e.length-g.hash.length))}}else if(dc.match(/^\w+:\/\//)){}else{var f=k.createElement(p);f.src=dc+q;dc=d(f.src)}if(i){i.parentNode.removeChild(i)}}
function rc(){var f=document.getElementsByTagName(r);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(s),b;if(h){if(h==t){b=e.getAttribute(u);if(b){var i,c=b.indexOf(v);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}nc[h]=i}}else if(h==w){b=e.getAttribute(u);if(b){try{sc=eval(b)}catch(a){alert(y+b+z)}}}else if(h==A){b=e.getAttribute(u);if(b){try{qc=eval(b)}catch(a){alert(y+b+B)}}}}}}
function wc(d,e){var a=cc;for(var b=0,c=d.length-1;b<c;++b){a=a[d[b]]||(a[d[b]]=[])}a[d[c]]=e}
function fc(d){var e=tc[d](),b=xc[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(sc){sc(d,a,e)}throw null}
tc[C]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(D)!=-1){return D}else if(d.indexOf(E)!=-1){return F}else if(d.indexOf(ab)!=-1){var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=6000){return bb}}}else if(d.indexOf(db)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return eb}return db}return fb};xc[C]={gecko:0,gecko1_8:1,ie6:2,opera:3,safari:4};com_google_gwt_demos_spinner_SpinnerDemo.onInjectionDone=function(){uc=true;Eb&&Eb(m,x,gb,{millis:(new Date()).getTime()});mc()};com_google_gwt_demos_spinner_SpinnerDemo.onScriptLoad=function(){if(ic){kc=true;mc()}};gc();rc();var vc;if(jc()){vc=hb}else{try{wc([bb],ib);wc([eb],jb);wc([D],kb);wc([db],lb);wc([F],mb);vc=cc[fc(C)]}catch(a){return}}var pc;function oc(){if(!ec){ec=true;if(!__gwt_stylesLoaded[ob]){var a=k.createElement(pb);__gwt_stylesLoaded[ob]=a;a.setAttribute(qb,rb);a.setAttribute(sb,dc+ob);k.getElementsByTagName(tb)[0].appendChild(a)}mc();if(k.removeEventListener){k.removeEventListener(ub,oc,false)}if(pc){clearInterval(pc)}}}
var ic;function lc(){if(!ic){ic=true;var a=k.createElement(vb);a.src=wb;a.id=m;a.style.cssText=xb;a.tabIndex=-1;k.body.appendChild(a);a.contentWindow.location.replace(dc+vc)}}
if(k.addEventListener){k.addEventListener(ub,function(){lc();oc()},false)}var pc=setInterval(function(){if(/loaded|complete/.test(k.readyState)){lc();oc()}},50);k.write(zb)}
com_google_gwt_demos_spinner_SpinnerDemo.__gwt_initHandlers=function(i,e,j){var d=window,g=d.onresize,f=d.onbeforeunload,h=d.onunload;d.onresize=function(a){try{i()}finally{g&&g(a)}};d.onbeforeunload=function(a){var c,b;try{c=e()}finally{b=f&&f(a)}if(c!=null){return c}if(b!=null){return b}};d.onunload=function(a){try{j()}finally{h&&h(a)}}};com_google_gwt_demos_spinner_SpinnerDemo();