function com_google_gwt_demos_styleinjector_StyleInjectorDemo(){var l='',B='" for "gwt:onLoadErrorFn"',z='" for "gwt:onPropertyErrorFn"',ub='"><\/script>',n='/',jb='0B498FC1B0DFA75F2886A659C8514059.cache.html',tb='<script id="',qb="<script>com_google_gwt_demos_styleinjector_StyleInjectorDemo.onInjectionDone('com.google.gwt.demos.styleinjector.StyleInjectorDemo')<\/script>",v='=',kb='AC3952513818EBD2DED48BC20CD0A6C0.cache.html',y='Bad handler "',ib='DABE6E2B5441A14283DEA5E36B67678D.cache.html',lb='DOMContentLoaded',vb='SCRIPT',sb='__gwt_marker_com.google.gwt.demos.styleinjector.StyleInjectorDemo',o='base',q='clear.cache.gif',m='com.google.gwt.demos.styleinjector.StyleInjectorDemo',u='content',db='gecko',eb='gecko1_8',nb='gwt.hybrid',A='gwt:onLoadErrorFn',w='gwt:onPropertyErrorFn',t='gwt:property',hb='hosted.html?com_google_gwt_demos_styleinjector_StyleInjectorDemo',bb='ie6',mb='iframe',p='img',ob="javascript:''",r='meta',gb='moduleRequested',ab='msie',s='name',D='opera',pb='position:absolute;width:0;height:0;border:none',F='safari',rb='selectionDone',cb='selectionStart',x='startup',fb='unknown',C='user.agent',E='webkit';var xb=window,k=document,Fb=xb.external,wb=xb.__gwtstatsEvent?function(a,b,c,d){xb.__gwtstatsEvent(a,b,c,d)}:null,mc,cc,Cb,Bb=l,fc={},pc=[],lc=[],Ab=[],ic,kc;wb&&wb(m,x,cb,{millis:(new Date()).getTime()});if(!xb.__gwt_stylesLoaded){xb.__gwt_stylesLoaded={}}if(!xb.__gwt_scriptsLoaded){xb.__gwt_scriptsLoaded={}}function bc(){try{return Fb&&(Fb.gwtOnLoad&&xb.location.search.indexOf(nb)==-1)}catch(a){return false}}
function ec(){if(mc&&cc){var c=k.getElementById(m);var b=c.contentWindow;b.__gwt_initHandlers=com_google_gwt_demos_styleinjector_StyleInjectorDemo.__gwt_initHandlers;if(bc()){b.__gwt_getProperty=function(a){return Db(a)}}com_google_gwt_demos_styleinjector_StyleInjectorDemo=null;b.gwtOnLoad(ic,m,Bb);wb&&wb(m,x,rb,{millis:(new Date()).getTime()})}}
function Eb(){var j,h=sb,i;k.write(tb+h+ub);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=vb){j=j.previousSibling}function d(b){var a=b.lastIndexOf(n);return a>=0?b.substring(0,a+1):l}
;if(j&&j.src){Bb=d(j.src)}if(Bb==l){var c=k.getElementsByTagName(o);if(c.length>0){Bb=c[c.length-1].href}else{var g=k.location;var e=g.href;Bb=d(e.substr(0,e.length-g.hash.length))}}else if(Bb.match(/^\w+:\/\//)){}else{var f=k.createElement(p);f.src=Bb+q;Bb=d(f.src)}if(i){i.parentNode.removeChild(i)}}
function jc(){var f=document.getElementsByTagName(r);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(s),b;if(h){if(h==t){b=e.getAttribute(u);if(b){var i,c=b.indexOf(v);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}fc[h]=i}}else if(h==w){b=e.getAttribute(u);if(b){try{kc=eval(b)}catch(a){alert(y+b+z)}}}else if(h==A){b=e.getAttribute(u);if(b){try{ic=eval(b)}catch(a){alert(y+b+B)}}}}}}
function oc(d,e){var a=Ab;for(var b=0,c=d.length-1;b<c;++b){a=a[d[b]]||(a[d[b]]=[])}a[d[c]]=e}
function Db(d){var e=lc[d](),b=pc[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(kc){kc(d,a,e)}throw null}
lc[C]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(D)!=-1){return D}else if(d.indexOf(E)!=-1){return F}else if(d.indexOf(ab)!=-1){var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=6000){return bb}}}else if(d.indexOf(db)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return eb}return db}return fb};pc[C]={gecko:0,gecko1_8:1,ie6:2,opera:3,safari:4};com_google_gwt_demos_styleinjector_StyleInjectorDemo.onInjectionDone=function(){mc=true;wb&&wb(m,x,gb,{millis:(new Date()).getTime()});ec()};com_google_gwt_demos_styleinjector_StyleInjectorDemo.onScriptLoad=function(){cc=true;ec()};Eb();jc();var nc;if(bc()){nc=hb}else{try{oc([F],ib);oc([db],jb);oc([eb],jb);oc([D],jb);oc([bb],kb);nc=Ab[Db(C)]}catch(a){return}}var hc;function gc(){if(!Cb){Cb=true;ec();if(k.removeEventListener){k.removeEventListener(lb,gc,false)}if(hc){clearInterval(hc)}}}
var ac;function dc(){if(!ac){ac=true;var a=k.createElement(mb);a.src=ob;a.id=m;a.style.cssText=pb;a.tabIndex=-1;k.body.appendChild(a);a.src=Bb+nc}}
if(k.addEventListener){k.addEventListener(lb,function(){dc();gc()},false)}var hc=setInterval(function(){if(/loaded|complete/.test(k.readyState)){dc();gc()}},50);k.write(qb)}
com_google_gwt_demos_styleinjector_StyleInjectorDemo.__gwt_initHandlers=function(i,e,j){var d=window,g=d.onresize,f=d.onbeforeunload,h=d.onunload;d.onresize=function(a){try{i()}finally{g&&g(a)}};d.onbeforeunload=function(a){var c,b;try{c=e()}finally{b=f&&f(a)}if(c!=null){return c}if(b!=null){return b}};d.onunload=function(a){try{j()}finally{h&&h(a)}}};com_google_gwt_demos_styleinjector_StyleInjectorDemo();